#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_SQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token2 = 6,
  anon_sym_SLASH_SLASH = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_SLASH_STAR = 9,
  aux_sym_comment_token2 = 10,
  anon_sym_SLASH = 11,
  anon_sym_EQ = 12,
  anon_sym_POUND = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_println = 16,
  anon_sym_return = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_def = 21,
  anon_sym_COMMA = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_source_file = 25,
  sym_string = 26,
  sym_comment = 27,
  sym__statement = 28,
  sym__assignment_definition = 29,
  sym_left_hand_side = 30,
  sym_right_hand_side = 31,
  sym_hash_like_function = 32,
  sym__simple_statement = 33,
  sym_print_statement = 34,
  sym_return_statement = 35,
  sym__expression = 36,
  sym_binary_expression = 37,
  sym_function_definition = 38,
  sym_parameters = 39,
  sym_function_body = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_parameters_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_POUND] = "#",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_println] = "println",
  [anon_sym_return] = "return",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_def] = "def",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym__statement] = "_statement",
  [sym__assignment_definition] = "_assignment_definition",
  [sym_left_hand_side] = "left_hand_side",
  [sym_right_hand_side] = "right_hand_side",
  [sym_hash_like_function] = "hash_like_function",
  [sym__simple_statement] = "_simple_statement",
  [sym_print_statement] = "print_statement",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_function_definition] = "function_definition",
  [sym_parameters] = "parameters",
  [sym_function_body] = "function_body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_println] = anon_sym_println,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym__statement] = sym__statement,
  [sym__assignment_definition] = sym__assignment_definition,
  [sym_left_hand_side] = sym_left_hand_side,
  [sym_right_hand_side] = sym_right_hand_side,
  [sym_hash_like_function] = sym_hash_like_function,
  [sym__simple_statement] = sym__simple_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_definition] = sym_function_definition,
  [sym_parameters] = sym_parameters,
  [sym_function_body] = sym_function_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_println] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_left_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_right_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_like_function] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 4,
  [8] = 6,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 11,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 12,
  [22] = 13,
  [23] = 19,
  [24] = 18,
  [25] = 15,
  [26] = 20,
  [27] = 14,
  [28] = 16,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 36,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 41,
  [44] = 39,
  [45] = 45,
  [46] = 31,
  [47] = 47,
  [48] = 32,
  [49] = 33,
  [50] = 45,
  [51] = 37,
  [52] = 47,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 59,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 63,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 66,
  [70] = 70,
  [71] = 67,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 82,
  [86] = 83,
  [87] = 73,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 79,
  [94] = 78,
  [95] = 95,
  [96] = 89,
  [97] = 90,
  [98] = 76,
  [99] = 80,
  [100] = 81,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 27,
        '#', 47,
        '\'', 23,
        '(', 48,
        ')', 49,
        '*', 54,
        '+', 52,
        ',', 56,
        '-', 53,
        '/', 45,
        '=', 46,
        'd', 8,
        'p', 16,
        'r', 9,
        '{', 57,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_println);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 25},
  [79] = {.lex_state = 29},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 37},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 29},
  [94] = {.lex_state = 25},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {(TSStateId)(-1)},
  [102] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_println] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(74),
    [sym_string] = STATE(13),
    [sym_comment] = STATE(1),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(38),
    [sym_left_hand_side] = STATE(82),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(38),
    [sym_print_statement] = STATE(51),
    [sym_return_statement] = STATE(51),
    [sym__expression] = STATE(18),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [2] = {
    [sym_string] = STATE(13),
    [sym_comment] = STATE(2),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(38),
    [sym_left_hand_side] = STATE(82),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(38),
    [sym_print_statement] = STATE(51),
    [sym_return_statement] = STATE(51),
    [sym__expression] = STATE(18),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [3] = {
    [sym_string] = STATE(13),
    [sym_comment] = STATE(3),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(38),
    [sym_left_hand_side] = STATE(82),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(38),
    [sym_print_statement] = STATE(51),
    [sym_return_statement] = STATE(51),
    [sym__expression] = STATE(18),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_number] = ACTIONS(34),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(46),
    [anon_sym_println] = ACTIONS(49),
    [anon_sym_return] = ACTIONS(52),
    [anon_sym_def] = ACTIONS(55),
  },
  [4] = {
    [sym_string] = STATE(22),
    [sym_comment] = STATE(4),
    [sym__statement] = STATE(35),
    [sym__assignment_definition] = STATE(36),
    [sym_left_hand_side] = STATE(85),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(36),
    [sym_print_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(22),
    [sym_function_definition] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(74),
  },
  [5] = {
    [sym_string] = STATE(22),
    [sym_comment] = STATE(5),
    [sym__statement] = STATE(35),
    [sym__assignment_definition] = STATE(36),
    [sym_left_hand_side] = STATE(85),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(36),
    [sym_print_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(22),
    [sym_function_definition] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(76),
    [sym_number] = ACTIONS(79),
    [anon_sym_SQUOTE] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(88),
    [anon_sym_println] = ACTIONS(91),
    [anon_sym_return] = ACTIONS(94),
    [anon_sym_def] = ACTIONS(97),
    [anon_sym_RBRACE] = ACTIONS(29),
  },
  [6] = {
    [sym_string] = STATE(22),
    [sym_comment] = STATE(6),
    [sym__statement] = STATE(35),
    [sym__assignment_definition] = STATE(36),
    [sym_left_hand_side] = STATE(85),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(36),
    [sym_print_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(22),
    [sym_function_definition] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(100),
  },
  [7] = {
    [sym_string] = STATE(22),
    [sym_comment] = STATE(7),
    [sym__statement] = STATE(35),
    [sym__assignment_definition] = STATE(36),
    [sym_left_hand_side] = STATE(85),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(36),
    [sym_print_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(22),
    [sym_function_definition] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(102),
  },
  [8] = {
    [sym_string] = STATE(22),
    [sym_comment] = STATE(8),
    [sym__statement] = STATE(35),
    [sym__assignment_definition] = STATE(36),
    [sym_left_hand_side] = STATE(85),
    [sym_hash_like_function] = STATE(72),
    [sym__simple_statement] = STATE(36),
    [sym_print_statement] = STATE(37),
    [sym_return_statement] = STATE(37),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(22),
    [sym_function_definition] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(104),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_println,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_def,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    STATE(20), 1,
      sym__expression,
    STATE(40), 1,
      sym_right_hand_side,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
    STATE(41), 2,
      sym__simple_statement,
      sym_function_definition,
    STATE(51), 2,
      sym_print_statement,
      sym_return_statement,
  [52] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      anon_sym_println,
    ACTIONS(70), 1,
      anon_sym_return,
    ACTIONS(72), 1,
      anon_sym_def,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(26), 1,
      sym__expression,
    STATE(42), 1,
      sym_right_hand_side,
    STATE(22), 2,
      sym_string,
      sym_binary_expression,
    STATE(37), 2,
      sym_print_statement,
      sym_return_statement,
    STATE(43), 2,
      sym__simple_statement,
      sym_function_definition,
  [104] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(11), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [135] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [164] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [193] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [222] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [251] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(130), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [280] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(17), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [311] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(134), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [343] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [375] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [407] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [435] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [463] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 1,
      anon_sym_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [495] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 1,
      anon_sym_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(134), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(132), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [527] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [555] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 1,
      anon_sym_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [587] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [615] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(130), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [643] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_println,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(19), 1,
      sym__expression,
    STATE(29), 1,
      sym_comment,
    STATE(44), 1,
      sym__simple_statement,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
    STATE(51), 2,
      sym_print_statement,
      sym_return_statement,
  [688] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      anon_sym_println,
    ACTIONS(70), 1,
      anon_sym_return,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(23), 1,
      sym__expression,
    STATE(30), 1,
      sym_comment,
    STATE(39), 1,
      sym__simple_statement,
    STATE(22), 2,
      sym_string,
      sym_binary_expression,
    STATE(37), 2,
      sym_print_statement,
      sym_return_statement,
  [733] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [757] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [781] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [805] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [829] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [853] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(134), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(132), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [877] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(168), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(170), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [901] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(134), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [925] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [949] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [973] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [997] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1021] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1045] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1069] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(176), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(178), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1093] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1117] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 1,
      sym_comment,
    ACTIONS(180), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(182), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1141] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(48), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1165] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1189] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(176), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1213] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(51), 1,
      sym_comment,
    ACTIONS(168), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1237] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_comment,
    ACTIONS(180), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(182), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1261] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_comment,
    STATE(57), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1294] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_comment,
    STATE(58), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1327] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym__expression,
    STATE(55), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1357] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym__expression,
    STATE(56), 1,
      sym_comment,
    ACTIONS(60), 2,
      sym_identifier,
      sym_number,
    STATE(22), 2,
      sym_string,
      sym_binary_expression,
  [1387] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1408] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      anon_sym_SLASH,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1429] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(192), 1,
      sym_number,
    STATE(59), 1,
      sym_comment,
    STATE(89), 1,
      sym_string,
  [1451] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      sym_number,
    STATE(60), 1,
      sym_comment,
    STATE(96), 1,
      sym_string,
  [1473] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      sym_comment,
    STATE(62), 1,
      aux_sym_parameters_repeat1,
  [1492] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(62), 2,
      sym_comment,
      aux_sym_parameters_repeat1,
  [1509] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_comment,
    STATE(76), 1,
      sym_parameters,
  [1528] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_parameters_repeat1,
    STATE(64), 1,
      sym_comment,
  [1547] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      sym_identifier,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_comment,
    STATE(98), 1,
      sym_parameters,
  [1566] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_function_body,
    STATE(66), 1,
      sym_comment,
  [1582] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_function_body,
    STATE(67), 1,
      sym_comment,
  [1598] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(68), 1,
      sym_comment,
    STATE(91), 1,
      sym_parameters,
  [1614] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_function_body,
    STATE(69), 1,
      sym_comment,
  [1630] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(70), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1644] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_function_body,
    STATE(71), 1,
      sym_comment,
  [1660] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(72), 1,
      sym_comment,
  [1673] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      sym_comment,
  [1686] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      sym_comment,
  [1699] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(225), 1,
      aux_sym_comment_token2,
    STATE(75), 1,
      sym_comment,
  [1712] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_comment,
  [1725] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(229), 1,
      sym_identifier,
    STATE(77), 1,
      sym_comment,
  [1738] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(231), 1,
      aux_sym_string_token1,
    STATE(78), 1,
      sym_comment,
  [1751] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(233), 1,
      aux_sym_string_token2,
    STATE(79), 1,
      sym_comment,
  [1764] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      anon_sym_LPAREN,
    STATE(80), 1,
      sym_comment,
  [1777] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      sym_identifier,
    STATE(81), 1,
      sym_comment,
  [1790] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      anon_sym_EQ,
    STATE(82), 1,
      sym_comment,
  [1803] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(217), 1,
      anon_sym_SQUOTE,
    STATE(83), 1,
      sym_comment,
  [1816] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_comment,
  [1829] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(243), 1,
      anon_sym_EQ,
    STATE(85), 1,
      sym_comment,
  [1842] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    STATE(86), 1,
      sym_comment,
  [1855] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_comment,
  [1868] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(247), 1,
      aux_sym_comment_token1,
    STATE(88), 1,
      sym_comment,
  [1881] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_comment,
  [1894] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      sym_comment,
  [1907] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym_comment,
  [1920] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(255), 1,
      anon_sym_EQ,
    STATE(92), 1,
      sym_comment,
  [1933] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(257), 1,
      aux_sym_string_token2,
    STATE(93), 1,
      sym_comment,
  [1946] = 4,
    ACTIONS(221), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(223), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(259), 1,
      aux_sym_string_token1,
    STATE(94), 1,
      sym_comment,
  [1959] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(261), 1,
      anon_sym_SLASH,
    STATE(95), 1,
      sym_comment,
  [1972] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_comment,
  [1985] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(265), 1,
      anon_sym_LPAREN,
    STATE(97), 1,
      sym_comment,
  [1998] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      sym_comment,
  [2011] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
    STATE(99), 1,
      sym_comment,
  [2024] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(271), 1,
      sym_identifier,
    STATE(100), 1,
      sym_comment,
  [2037] = 1,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [2041] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 52,
  [SMALL_STATE(11)] = 104,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 164,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 222,
  [SMALL_STATE(16)] = 251,
  [SMALL_STATE(17)] = 280,
  [SMALL_STATE(18)] = 311,
  [SMALL_STATE(19)] = 343,
  [SMALL_STATE(20)] = 375,
  [SMALL_STATE(21)] = 407,
  [SMALL_STATE(22)] = 435,
  [SMALL_STATE(23)] = 463,
  [SMALL_STATE(24)] = 495,
  [SMALL_STATE(25)] = 527,
  [SMALL_STATE(26)] = 555,
  [SMALL_STATE(27)] = 587,
  [SMALL_STATE(28)] = 615,
  [SMALL_STATE(29)] = 643,
  [SMALL_STATE(30)] = 688,
  [SMALL_STATE(31)] = 733,
  [SMALL_STATE(32)] = 757,
  [SMALL_STATE(33)] = 781,
  [SMALL_STATE(34)] = 805,
  [SMALL_STATE(35)] = 829,
  [SMALL_STATE(36)] = 853,
  [SMALL_STATE(37)] = 877,
  [SMALL_STATE(38)] = 901,
  [SMALL_STATE(39)] = 925,
  [SMALL_STATE(40)] = 949,
  [SMALL_STATE(41)] = 973,
  [SMALL_STATE(42)] = 997,
  [SMALL_STATE(43)] = 1021,
  [SMALL_STATE(44)] = 1045,
  [SMALL_STATE(45)] = 1069,
  [SMALL_STATE(46)] = 1093,
  [SMALL_STATE(47)] = 1117,
  [SMALL_STATE(48)] = 1141,
  [SMALL_STATE(49)] = 1165,
  [SMALL_STATE(50)] = 1189,
  [SMALL_STATE(51)] = 1213,
  [SMALL_STATE(52)] = 1237,
  [SMALL_STATE(53)] = 1261,
  [SMALL_STATE(54)] = 1294,
  [SMALL_STATE(55)] = 1327,
  [SMALL_STATE(56)] = 1357,
  [SMALL_STATE(57)] = 1387,
  [SMALL_STATE(58)] = 1408,
  [SMALL_STATE(59)] = 1429,
  [SMALL_STATE(60)] = 1451,
  [SMALL_STATE(61)] = 1473,
  [SMALL_STATE(62)] = 1492,
  [SMALL_STATE(63)] = 1509,
  [SMALL_STATE(64)] = 1528,
  [SMALL_STATE(65)] = 1547,
  [SMALL_STATE(66)] = 1566,
  [SMALL_STATE(67)] = 1582,
  [SMALL_STATE(68)] = 1598,
  [SMALL_STATE(69)] = 1614,
  [SMALL_STATE(70)] = 1630,
  [SMALL_STATE(71)] = 1644,
  [SMALL_STATE(72)] = 1660,
  [SMALL_STATE(73)] = 1673,
  [SMALL_STATE(74)] = 1686,
  [SMALL_STATE(75)] = 1699,
  [SMALL_STATE(76)] = 1712,
  [SMALL_STATE(77)] = 1725,
  [SMALL_STATE(78)] = 1738,
  [SMALL_STATE(79)] = 1751,
  [SMALL_STATE(80)] = 1764,
  [SMALL_STATE(81)] = 1777,
  [SMALL_STATE(82)] = 1790,
  [SMALL_STATE(83)] = 1803,
  [SMALL_STATE(84)] = 1816,
  [SMALL_STATE(85)] = 1829,
  [SMALL_STATE(86)] = 1842,
  [SMALL_STATE(87)] = 1855,
  [SMALL_STATE(88)] = 1868,
  [SMALL_STATE(89)] = 1881,
  [SMALL_STATE(90)] = 1894,
  [SMALL_STATE(91)] = 1907,
  [SMALL_STATE(92)] = 1920,
  [SMALL_STATE(93)] = 1933,
  [SMALL_STATE(94)] = 1946,
  [SMALL_STATE(95)] = 1959,
  [SMALL_STATE(96)] = 1972,
  [SMALL_STATE(97)] = 1985,
  [SMALL_STATE(98)] = 1998,
  [SMALL_STATE(99)] = 2011,
  [SMALL_STATE(100)] = 2024,
  [SMALL_STATE(101)] = 2037,
  [SMALL_STATE(102)] = 2041,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_left_hand_side, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [219] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_like_function, 4, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zoomba(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
