#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_SQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token2 = 6,
  anon_sym_SLASH_SLASH = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_SLASH_STAR = 9,
  aux_sym_comment_token2 = 10,
  anon_sym_SLASH = 11,
  anon_sym_EQ = 12,
  anon_sym_POUND = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_println = 16,
  anon_sym_return = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_def = 21,
  anon_sym_COMMA = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_source_file = 25,
  sym_string = 26,
  sym_comment = 27,
  sym__statement = 28,
  sym__assignment_definition = 29,
  sym_left_hand_side = 30,
  sym_right_hand_side = 31,
  sym_hash_like_function = 32,
  sym__simple_statement = 33,
  sym_print_statement = 34,
  sym_return_statement = 35,
  sym__expression = 36,
  sym_binary_expression = 37,
  sym_function_definition = 38,
  sym_parameters = 39,
  sym_function_body = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_parameters_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_POUND] = "#",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_println] = "println",
  [anon_sym_return] = "return",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_def] = "def",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym__statement] = "_statement",
  [sym__assignment_definition] = "_assignment_definition",
  [sym_left_hand_side] = "left_hand_side",
  [sym_right_hand_side] = "right_hand_side",
  [sym_hash_like_function] = "hash_like_function",
  [sym__simple_statement] = "_simple_statement",
  [sym_print_statement] = "print_statement",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_function_definition] = "function_definition",
  [sym_parameters] = "parameters",
  [sym_function_body] = "function_body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_println] = anon_sym_println,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym__statement] = sym__statement,
  [sym__assignment_definition] = sym__assignment_definition,
  [sym_left_hand_side] = sym_left_hand_side,
  [sym_right_hand_side] = sym_right_hand_side,
  [sym_hash_like_function] = sym_hash_like_function,
  [sym__simple_statement] = sym__simple_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_definition] = sym_function_definition,
  [sym_parameters] = sym_parameters,
  [sym_function_body] = sym_function_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_println] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_left_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_right_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_like_function] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 2,
  [8] = 5,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 13,
  [20] = 14,
  [21] = 18,
  [22] = 15,
  [23] = 12,
  [24] = 17,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 26,
  [38] = 36,
  [39] = 27,
  [40] = 28,
  [41] = 29,
  [42] = 30,
  [43] = 25,
  [44] = 32,
  [45] = 33,
  [46] = 35,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 49,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 58,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 64,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 74,
  [81] = 81,
  [82] = 82,
  [83] = 72,
  [84] = 84,
  [85] = 81,
  [86] = 86,
  [87] = 87,
  [88] = 87,
  [89] = 76,
  [90] = 79,
  [91] = 91,
  [92] = 92,
  [93] = 77,
  [94] = 82,
  [95] = 71,
  [96] = 70,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 26,
        '#', 46,
        '\'', 22,
        '(', 47,
        ')', 48,
        '*', 53,
        '+', 51,
        ',', 55,
        '-', 52,
        '/', 44,
        '=', 45,
        'd', 7,
        'p', 15,
        'r', 8,
        '{', 56,
        '}', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_println);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 28},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 36},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 24},
  [88] = {.lex_state = 24},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {(TSStateId)(-1)},
  [98] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_println] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(78),
    [sym_string] = STATE(13),
    [sym_comment] = STATE(1),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(46),
    [sym_left_hand_side] = STATE(90),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(46),
    [sym_print_statement] = STATE(38),
    [sym_return_statement] = STATE(38),
    [sym__expression] = STATE(17),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [2] = {
    [sym_string] = STATE(13),
    [sym_comment] = STATE(2),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(46),
    [sym_left_hand_side] = STATE(90),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(46),
    [sym_print_statement] = STATE(38),
    [sym_return_statement] = STATE(38),
    [sym__expression] = STATE(17),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_number] = ACTIONS(32),
    [anon_sym_SQUOTE] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(38),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_println] = ACTIONS(47),
    [anon_sym_return] = ACTIONS(50),
    [anon_sym_def] = ACTIONS(53),
  },
  [3] = {
    [sym_string] = STATE(13),
    [sym_comment] = STATE(3),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(46),
    [sym_left_hand_side] = STATE(90),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(46),
    [sym_print_statement] = STATE(38),
    [sym_return_statement] = STATE(38),
    [sym__expression] = STATE(17),
    [sym_binary_expression] = STATE(13),
    [sym_function_definition] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [4] = {
    [sym_string] = STATE(19),
    [sym_comment] = STATE(4),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(79),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(19),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(74),
  },
  [5] = {
    [sym_string] = STATE(19),
    [sym_comment] = STATE(5),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(79),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(19),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(76),
  },
  [6] = {
    [sym_string] = STATE(19),
    [sym_comment] = STATE(6),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(79),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(19),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(78),
  },
  [7] = {
    [sym_string] = STATE(19),
    [sym_comment] = STATE(7),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(79),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(19),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(80),
    [sym_number] = ACTIONS(83),
    [anon_sym_SQUOTE] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(92),
    [anon_sym_println] = ACTIONS(95),
    [anon_sym_return] = ACTIONS(98),
    [anon_sym_def] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(27),
  },
  [8] = {
    [sym_string] = STATE(19),
    [sym_comment] = STATE(8),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(79),
    [sym_hash_like_function] = STATE(69),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(24),
    [sym_binary_expression] = STATE(19),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(62),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(68),
    [anon_sym_return] = ACTIONS(70),
    [anon_sym_def] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(104),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_println,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_def,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    STATE(18), 1,
      sym__expression,
    STATE(27), 1,
      sym_right_hand_side,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
    STATE(28), 2,
      sym__simple_statement,
      sym_function_definition,
    STATE(38), 2,
      sym_print_statement,
      sym_return_statement,
  [52] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      sym_number,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      anon_sym_println,
    ACTIONS(70), 1,
      anon_sym_return,
    ACTIONS(72), 1,
      anon_sym_def,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(21), 1,
      sym__expression,
    STATE(39), 1,
      sym_right_hand_side,
    STATE(19), 2,
      sym_string,
      sym_binary_expression,
    STATE(36), 2,
      sym_print_statement,
      sym_return_statement,
    STATE(40), 2,
      sym__simple_statement,
      sym_function_definition,
  [104] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(11), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [135] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [164] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [193] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [222] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [251] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(16), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [282] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [314] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [346] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [374] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [402] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(142), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [434] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [462] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [490] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(142), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [522] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [546] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(150), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [570] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [594] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [618] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [642] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [666] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [690] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(170), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [714] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [738] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [762] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [786] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(176), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(178), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [810] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(150), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(148), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [834] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(176), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [858] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [882] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [906] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [930] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [954] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(146), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(144), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [978] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(170), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(168), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1002] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1026] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1050] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym__expression,
    STATE(47), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1080] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym__expression,
    STATE(48), 1,
      sym_comment,
    ACTIONS(60), 2,
      sym_identifier,
      sym_number,
    STATE(19), 2,
      sym_string,
      sym_binary_expression,
  [1110] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(49), 1,
      sym_comment,
    STATE(51), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1140] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_comment,
    STATE(52), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_string,
      sym_binary_expression,
  [1170] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1191] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1212] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      sym_number,
    STATE(26), 1,
      sym_string,
    STATE(53), 1,
      sym_comment,
  [1234] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      sym_number,
    STATE(37), 1,
      sym_string,
    STATE(54), 1,
      sym_comment,
  [1256] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 1,
      sym_number,
    STATE(55), 1,
      sym_comment,
    STATE(72), 1,
      sym_string,
  [1278] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_number,
    STATE(56), 1,
      sym_comment,
    STATE(83), 1,
      sym_string,
  [1300] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_parameters_repeat1,
  [1319] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      sym_comment,
    STATE(77), 1,
      sym_parameters,
  [1338] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(59), 2,
      sym_comment,
      aux_sym_parameters_repeat1,
  [1355] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_parameters_repeat1,
    STATE(60), 1,
      sym_comment,
  [1374] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      sym_comment,
    STATE(93), 1,
      sym_parameters,
  [1393] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      sym_identifier,
    STATE(62), 1,
      sym_comment,
    STATE(92), 1,
      sym_parameters,
  [1409] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_function_body,
    STATE(63), 1,
      sym_comment,
  [1425] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_function_body,
    STATE(64), 1,
      sym_comment,
  [1441] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(65), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1455] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_function_body,
    STATE(66), 1,
      sym_comment,
  [1471] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_function_body,
    STATE(67), 1,
      sym_comment,
  [1487] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      anon_sym_EQ,
    STATE(68), 1,
      sym_comment,
  [1500] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(69), 1,
      sym_comment,
  [1513] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(70), 1,
      sym_comment,
  [1526] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
    STATE(71), 1,
      sym_comment,
  [1539] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      sym_comment,
  [1552] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      anon_sym_SLASH,
    STATE(73), 1,
      sym_comment,
  [1565] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(223), 1,
      anon_sym_SQUOTE,
    STATE(74), 1,
      sym_comment,
  [1578] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    STATE(75), 1,
      sym_comment,
  [1591] = 4,
    ACTIONS(227), 1,
      aux_sym_string_token2,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    STATE(76), 1,
      sym_comment,
  [1604] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_comment,
  [1617] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
    STATE(78), 1,
      sym_comment,
  [1630] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      anon_sym_EQ,
    STATE(79), 1,
      sym_comment,
  [1643] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    STATE(80), 1,
      sym_comment,
  [1656] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      sym_comment,
  [1669] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      anon_sym_LPAREN,
    STATE(82), 1,
      sym_comment,
  [1682] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym_comment,
  [1695] = 4,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      aux_sym_comment_token1,
    STATE(84), 1,
      sym_comment,
  [1708] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_comment,
  [1721] = 4,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(247), 1,
      aux_sym_comment_token2,
    STATE(86), 1,
      sym_comment,
  [1734] = 4,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(249), 1,
      aux_sym_string_token1,
    STATE(87), 1,
      sym_comment,
  [1747] = 4,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 1,
      aux_sym_string_token1,
    STATE(88), 1,
      sym_comment,
  [1760] = 4,
    ACTIONS(229), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(231), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      aux_sym_string_token2,
    STATE(89), 1,
      sym_comment,
  [1773] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(255), 1,
      anon_sym_EQ,
    STATE(90), 1,
      sym_comment,
  [1786] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(257), 1,
      sym_identifier,
    STATE(91), 1,
      sym_comment,
  [1799] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      sym_comment,
  [1812] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_comment,
  [1825] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(263), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_comment,
  [1838] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(265), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      sym_comment,
  [1851] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(96), 1,
      sym_comment,
  [1864] = 1,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
  [1868] = 1,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 52,
  [SMALL_STATE(11)] = 104,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 164,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 222,
  [SMALL_STATE(16)] = 251,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 314,
  [SMALL_STATE(19)] = 346,
  [SMALL_STATE(20)] = 374,
  [SMALL_STATE(21)] = 402,
  [SMALL_STATE(22)] = 434,
  [SMALL_STATE(23)] = 462,
  [SMALL_STATE(24)] = 490,
  [SMALL_STATE(25)] = 522,
  [SMALL_STATE(26)] = 546,
  [SMALL_STATE(27)] = 570,
  [SMALL_STATE(28)] = 594,
  [SMALL_STATE(29)] = 618,
  [SMALL_STATE(30)] = 642,
  [SMALL_STATE(31)] = 666,
  [SMALL_STATE(32)] = 690,
  [SMALL_STATE(33)] = 714,
  [SMALL_STATE(34)] = 738,
  [SMALL_STATE(35)] = 762,
  [SMALL_STATE(36)] = 786,
  [SMALL_STATE(37)] = 810,
  [SMALL_STATE(38)] = 834,
  [SMALL_STATE(39)] = 858,
  [SMALL_STATE(40)] = 882,
  [SMALL_STATE(41)] = 906,
  [SMALL_STATE(42)] = 930,
  [SMALL_STATE(43)] = 954,
  [SMALL_STATE(44)] = 978,
  [SMALL_STATE(45)] = 1002,
  [SMALL_STATE(46)] = 1026,
  [SMALL_STATE(47)] = 1050,
  [SMALL_STATE(48)] = 1080,
  [SMALL_STATE(49)] = 1110,
  [SMALL_STATE(50)] = 1140,
  [SMALL_STATE(51)] = 1170,
  [SMALL_STATE(52)] = 1191,
  [SMALL_STATE(53)] = 1212,
  [SMALL_STATE(54)] = 1234,
  [SMALL_STATE(55)] = 1256,
  [SMALL_STATE(56)] = 1278,
  [SMALL_STATE(57)] = 1300,
  [SMALL_STATE(58)] = 1319,
  [SMALL_STATE(59)] = 1338,
  [SMALL_STATE(60)] = 1355,
  [SMALL_STATE(61)] = 1374,
  [SMALL_STATE(62)] = 1393,
  [SMALL_STATE(63)] = 1409,
  [SMALL_STATE(64)] = 1425,
  [SMALL_STATE(65)] = 1441,
  [SMALL_STATE(66)] = 1455,
  [SMALL_STATE(67)] = 1471,
  [SMALL_STATE(68)] = 1487,
  [SMALL_STATE(69)] = 1500,
  [SMALL_STATE(70)] = 1513,
  [SMALL_STATE(71)] = 1526,
  [SMALL_STATE(72)] = 1539,
  [SMALL_STATE(73)] = 1552,
  [SMALL_STATE(74)] = 1565,
  [SMALL_STATE(75)] = 1578,
  [SMALL_STATE(76)] = 1591,
  [SMALL_STATE(77)] = 1604,
  [SMALL_STATE(78)] = 1617,
  [SMALL_STATE(79)] = 1630,
  [SMALL_STATE(80)] = 1643,
  [SMALL_STATE(81)] = 1656,
  [SMALL_STATE(82)] = 1669,
  [SMALL_STATE(83)] = 1682,
  [SMALL_STATE(84)] = 1695,
  [SMALL_STATE(85)] = 1708,
  [SMALL_STATE(86)] = 1721,
  [SMALL_STATE(87)] = 1734,
  [SMALL_STATE(88)] = 1747,
  [SMALL_STATE(89)] = 1760,
  [SMALL_STATE(90)] = 1773,
  [SMALL_STATE(91)] = 1786,
  [SMALL_STATE(92)] = 1799,
  [SMALL_STATE(93)] = 1812,
  [SMALL_STATE(94)] = 1825,
  [SMALL_STATE(95)] = 1838,
  [SMALL_STATE(96)] = 1851,
  [SMALL_STATE(97)] = 1864,
  [SMALL_STATE(98)] = 1868,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_left_hand_side, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_like_function, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zoomba(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
