#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 91
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_SQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token2 = 6,
  anon_sym_SLASH_SLASH = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_SLASH_STAR = 9,
  aux_sym_comment_token2 = 10,
  anon_sym_SLASH = 11,
  anon_sym_PLUS = 12,
  anon_sym_DASH = 13,
  anon_sym_STAR = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_def = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_EQ = 21,
  anon_sym_return = 22,
  anon_sym_println = 23,
  sym_source_file = 24,
  sym_string = 25,
  sym_comment = 26,
  sym__statement = 27,
  sym__statement_definition = 28,
  sym__expressions = 29,
  sym_binary_expression = 30,
  sym__function_definition = 31,
  sym_function_params = 32,
  sym_function_body = 33,
  sym_parameter = 34,
  sym_return_statement = 35,
  sym__simple_statements = 36,
  sym_print_statement = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_function_params_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_def] = "def",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_println] = "println",
  [sym_source_file] = "source_file",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym__statement] = "_statement",
  [sym__statement_definition] = "_statement_definition",
  [sym__expressions] = "_expressions",
  [sym_binary_expression] = "binary_expression",
  [sym__function_definition] = "_function_definition",
  [sym_function_params] = "function_params",
  [sym_function_body] = "function_body",
  [sym_parameter] = "parameter",
  [sym_return_statement] = "return_statement",
  [sym__simple_statements] = "_simple_statements",
  [sym_print_statement] = "print_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_params_repeat1] = "function_params_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_println] = anon_sym_println,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym__statement] = sym__statement,
  [sym__statement_definition] = sym__statement_definition,
  [sym__expressions] = sym__expressions,
  [sym_binary_expression] = sym_binary_expression,
  [sym__function_definition] = sym__function_definition,
  [sym_function_params] = sym_function_params,
  [sym_function_body] = sym_function_body,
  [sym_parameter] = sym_parameter,
  [sym_return_statement] = sym_return_statement,
  [sym__simple_statements] = sym__simple_statements,
  [sym_print_statement] = sym_print_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_params_repeat1] = aux_sym_function_params_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_println] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expressions] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__function_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_params] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_statements] = {
    .visible = false,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_params_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 3,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 9,
  [17] = 12,
  [18] = 10,
  [19] = 14,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 22,
  [31] = 31,
  [32] = 21,
  [33] = 29,
  [34] = 31,
  [35] = 25,
  [36] = 36,
  [37] = 37,
  [38] = 36,
  [39] = 37,
  [40] = 26,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 42,
  [45] = 43,
  [46] = 41,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 49,
  [51] = 51,
  [52] = 52,
  [53] = 51,
  [54] = 52,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 60,
  [63] = 63,
  [64] = 61,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 67,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 69,
  [81] = 79,
  [82] = 82,
  [83] = 83,
  [84] = 76,
  [85] = 72,
  [86] = 71,
  [87] = 83,
  [88] = 70,
  [89] = 89,
  [90] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 26,
        '\'', 22,
        '(', 48,
        ')', 49,
        '*', 47,
        '+', 45,
        ',', 51,
        '-', 46,
        '/', 44,
        '=', 54,
        'd', 7,
        'p', 15,
        'r', 8,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_println);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 36},
  [69] = {.lex_state = 24},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 28},
  [80] = {.lex_state = 24},
  [81] = {.lex_state = 28},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {(TSStateId)(-1)},
  [90] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_println] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(77),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(1),
    [sym__statement] = STATE(30),
    [sym__statement_definition] = STATE(24),
    [sym__expressions] = STATE(24),
    [sym_binary_expression] = STATE(14),
    [sym__function_definition] = STATE(24),
    [sym_return_statement] = STATE(35),
    [sym__simple_statements] = STATE(40),
    [sym_print_statement] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_def] = ACTIONS(19),
    [anon_sym_return] = ACTIONS(21),
    [anon_sym_println] = ACTIONS(23),
  },
  [2] = {
    [sym_string] = STATE(9),
    [sym_comment] = STATE(2),
    [sym__statement] = STATE(30),
    [sym__statement_definition] = STATE(24),
    [sym__expressions] = STATE(24),
    [sym_binary_expression] = STATE(14),
    [sym__function_definition] = STATE(24),
    [sym_return_statement] = STATE(35),
    [sym__simple_statements] = STATE(40),
    [sym_print_statement] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(30),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(36),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(42),
    [anon_sym_return] = ACTIONS(45),
    [anon_sym_println] = ACTIONS(48),
  },
  [3] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(3),
    [sym__statement] = STATE(22),
    [sym__statement_definition] = STATE(23),
    [sym__expressions] = STATE(23),
    [sym_binary_expression] = STATE(19),
    [sym__function_definition] = STATE(23),
    [sym_return_statement] = STATE(25),
    [sym__simple_statements] = STATE(26),
    [sym_print_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(51),
    [sym_number] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_def] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(63),
    [anon_sym_return] = ACTIONS(65),
    [anon_sym_println] = ACTIONS(67),
  },
  [4] = {
    [sym_string] = STATE(9),
    [sym_comment] = STATE(4),
    [sym__statement] = STATE(30),
    [sym__statement_definition] = STATE(24),
    [sym__expressions] = STATE(24),
    [sym_binary_expression] = STATE(14),
    [sym__function_definition] = STATE(24),
    [sym_return_statement] = STATE(35),
    [sym__simple_statements] = STATE(40),
    [sym_print_statement] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_def] = ACTIONS(19),
    [anon_sym_return] = ACTIONS(21),
    [anon_sym_println] = ACTIONS(23),
  },
  [5] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(5),
    [sym__statement] = STATE(22),
    [sym__statement_definition] = STATE(23),
    [sym__expressions] = STATE(23),
    [sym_binary_expression] = STATE(19),
    [sym__function_definition] = STATE(23),
    [sym_return_statement] = STATE(25),
    [sym__simple_statements] = STATE(26),
    [sym_print_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(51),
    [sym_number] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_def] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_return] = ACTIONS(65),
    [anon_sym_println] = ACTIONS(67),
  },
  [6] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(6),
    [sym__statement] = STATE(22),
    [sym__statement_definition] = STATE(23),
    [sym__expressions] = STATE(23),
    [sym_binary_expression] = STATE(19),
    [sym__function_definition] = STATE(23),
    [sym_return_statement] = STATE(25),
    [sym__simple_statements] = STATE(26),
    [sym_print_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(73),
    [sym_number] = ACTIONS(76),
    [anon_sym_SQUOTE] = ACTIONS(79),
    [anon_sym_DQUOTE] = ACTIONS(82),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_def] = ACTIONS(88),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_return] = ACTIONS(91),
    [anon_sym_println] = ACTIONS(94),
  },
  [7] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(7),
    [sym__statement] = STATE(22),
    [sym__statement_definition] = STATE(23),
    [sym__expressions] = STATE(23),
    [sym_binary_expression] = STATE(19),
    [sym__function_definition] = STATE(23),
    [sym_return_statement] = STATE(25),
    [sym__simple_statements] = STATE(26),
    [sym_print_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(51),
    [sym_number] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_def] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(97),
    [anon_sym_return] = ACTIONS(65),
    [anon_sym_println] = ACTIONS(67),
  },
  [8] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(8),
    [sym__statement] = STATE(22),
    [sym__statement_definition] = STATE(23),
    [sym__expressions] = STATE(23),
    [sym_binary_expression] = STATE(19),
    [sym__function_definition] = STATE(23),
    [sym_return_statement] = STATE(25),
    [sym__simple_statements] = STATE(26),
    [sym_print_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(51),
    [sym_number] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_def] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_return] = ACTIONS(65),
    [anon_sym_println] = ACTIONS(67),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_comment,
    ACTIONS(103), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [28] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(111), 1,
      anon_sym_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(107), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [60] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_comment,
    ACTIONS(107), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [88] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(107), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [116] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(115), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [144] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(111), 1,
      anon_sym_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(119), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [177] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(115), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(113), 8,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [204] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(103), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(101), 8,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [231] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(107), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 8,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [258] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(107), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 7,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [289] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(127), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(119), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(117), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [322] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(107), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(105), 8,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [349] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(129), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(131), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [372] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(133), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(135), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [395] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(137), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(139), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [418] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(137), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [441] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(141), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(143), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [464] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(145), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(147), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [487] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(149), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(151), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [510] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(149), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [533] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(155), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [556] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(133), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [579] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(159), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [602] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(129), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [625] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(155), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(153), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [648] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(159), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(157), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [671] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(141), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [694] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(161), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(163), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [717] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(165), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(167), 5,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [740] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(161), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [763] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(165), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [786] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(145), 4,
      sym_identifier,
      anon_sym_def,
      anon_sym_return,
      anon_sym_println,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
  [809] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_string,
    STATE(41), 1,
      sym_comment,
    STATE(47), 1,
      sym_binary_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [838] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_string,
    STATE(12), 1,
      sym_binary_expression,
    STATE(42), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [867] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_string,
    STATE(10), 1,
      sym_binary_expression,
    STATE(43), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [896] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_string,
    STATE(17), 1,
      sym_binary_expression,
    STATE(44), 1,
      sym_comment,
    ACTIONS(53), 2,
      sym_identifier,
      sym_number,
  [925] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_string,
    STATE(18), 1,
      sym_binary_expression,
    STATE(45), 1,
      sym_comment,
    ACTIONS(53), 2,
      sym_identifier,
      sym_number,
  [954] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_string,
    STATE(46), 1,
      sym_comment,
    STATE(48), 1,
      sym_binary_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [983] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1006] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(109), 1,
      anon_sym_SLASH,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1029] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_comment,
    STATE(57), 1,
      sym_parameter,
    STATE(72), 1,
      sym_function_params,
  [1051] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(173), 1,
      sym_identifier,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_comment,
    STATE(57), 1,
      sym_parameter,
    STATE(85), 1,
      sym_function_params,
  [1073] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      sym_number,
    STATE(28), 1,
      sym_string,
    STATE(51), 1,
      sym_comment,
  [1095] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      sym_number,
    STATE(52), 1,
      sym_comment,
    STATE(84), 1,
      sym_string,
  [1117] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_number,
    STATE(27), 1,
      sym_string,
    STATE(53), 1,
      sym_comment,
  [1139] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      sym_number,
    STATE(54), 1,
      sym_comment,
    STATE(76), 1,
      sym_string,
  [1161] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(189), 1,
      anon_sym_EQ,
    STATE(55), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1178] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(56), 2,
      sym_comment,
      aux_sym_function_params_repeat1,
  [1195] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      sym_comment,
    STATE(58), 1,
      aux_sym_function_params_repeat1,
  [1214] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym_function_params_repeat1,
    STATE(58), 1,
      sym_comment,
  [1233] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(59), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1247] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_function_body,
    STATE(60), 1,
      sym_comment,
  [1263] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_function_body,
    STATE(61), 1,
      sym_comment,
  [1279] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_function_body,
    STATE(62), 1,
      sym_comment,
  [1295] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(63), 1,
      sym_comment,
    STATE(65), 1,
      sym_parameter,
  [1311] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_function_body,
    STATE(64), 1,
      sym_comment,
  [1327] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(65), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1341] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(66), 1,
      sym_comment,
  [1354] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_comment,
  [1367] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(214), 1,
      aux_sym_comment_token1,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    STATE(68), 1,
      sym_comment,
  [1380] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_string_token1,
    STATE(69), 1,
      sym_comment,
  [1393] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(220), 1,
      sym_identifier,
    STATE(70), 1,
      sym_comment,
  [1406] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    STATE(71), 1,
      sym_comment,
  [1419] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      sym_comment,
  [1432] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(226), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      sym_comment,
  [1445] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(74), 1,
      sym_comment,
  [1458] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(210), 1,
      anon_sym_SQUOTE,
    STATE(75), 1,
      sym_comment,
  [1471] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_comment,
  [1484] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    STATE(77), 1,
      sym_comment,
  [1497] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(232), 1,
      aux_sym_comment_token2,
    STATE(78), 1,
      sym_comment,
  [1510] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(234), 1,
      aux_sym_string_token2,
    STATE(79), 1,
      sym_comment,
  [1523] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(236), 1,
      aux_sym_string_token1,
    STATE(80), 1,
      sym_comment,
  [1536] = 4,
    ACTIONS(212), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(238), 1,
      aux_sym_string_token2,
    STATE(81), 1,
      sym_comment,
  [1549] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(240), 1,
      anon_sym_SLASH,
    STATE(82), 1,
      sym_comment,
  [1562] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(242), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_comment,
  [1575] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_comment,
  [1588] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_comment,
  [1601] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_comment,
  [1614] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
    STATE(87), 1,
      sym_comment,
  [1627] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(88), 1,
      sym_comment,
  [1640] = 1,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
  [1644] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 28,
  [SMALL_STATE(11)] = 60,
  [SMALL_STATE(12)] = 88,
  [SMALL_STATE(13)] = 116,
  [SMALL_STATE(14)] = 144,
  [SMALL_STATE(15)] = 177,
  [SMALL_STATE(16)] = 204,
  [SMALL_STATE(17)] = 231,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 289,
  [SMALL_STATE(20)] = 322,
  [SMALL_STATE(21)] = 349,
  [SMALL_STATE(22)] = 372,
  [SMALL_STATE(23)] = 395,
  [SMALL_STATE(24)] = 418,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 464,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 510,
  [SMALL_STATE(29)] = 533,
  [SMALL_STATE(30)] = 556,
  [SMALL_STATE(31)] = 579,
  [SMALL_STATE(32)] = 602,
  [SMALL_STATE(33)] = 625,
  [SMALL_STATE(34)] = 648,
  [SMALL_STATE(35)] = 671,
  [SMALL_STATE(36)] = 694,
  [SMALL_STATE(37)] = 717,
  [SMALL_STATE(38)] = 740,
  [SMALL_STATE(39)] = 763,
  [SMALL_STATE(40)] = 786,
  [SMALL_STATE(41)] = 809,
  [SMALL_STATE(42)] = 838,
  [SMALL_STATE(43)] = 867,
  [SMALL_STATE(44)] = 896,
  [SMALL_STATE(45)] = 925,
  [SMALL_STATE(46)] = 954,
  [SMALL_STATE(47)] = 983,
  [SMALL_STATE(48)] = 1006,
  [SMALL_STATE(49)] = 1029,
  [SMALL_STATE(50)] = 1051,
  [SMALL_STATE(51)] = 1073,
  [SMALL_STATE(52)] = 1095,
  [SMALL_STATE(53)] = 1117,
  [SMALL_STATE(54)] = 1139,
  [SMALL_STATE(55)] = 1161,
  [SMALL_STATE(56)] = 1178,
  [SMALL_STATE(57)] = 1195,
  [SMALL_STATE(58)] = 1214,
  [SMALL_STATE(59)] = 1233,
  [SMALL_STATE(60)] = 1247,
  [SMALL_STATE(61)] = 1263,
  [SMALL_STATE(62)] = 1279,
  [SMALL_STATE(63)] = 1295,
  [SMALL_STATE(64)] = 1311,
  [SMALL_STATE(65)] = 1327,
  [SMALL_STATE(66)] = 1341,
  [SMALL_STATE(67)] = 1354,
  [SMALL_STATE(68)] = 1367,
  [SMALL_STATE(69)] = 1380,
  [SMALL_STATE(70)] = 1393,
  [SMALL_STATE(71)] = 1406,
  [SMALL_STATE(72)] = 1419,
  [SMALL_STATE(73)] = 1432,
  [SMALL_STATE(74)] = 1445,
  [SMALL_STATE(75)] = 1458,
  [SMALL_STATE(76)] = 1471,
  [SMALL_STATE(77)] = 1484,
  [SMALL_STATE(78)] = 1497,
  [SMALL_STATE(79)] = 1510,
  [SMALL_STATE(80)] = 1523,
  [SMALL_STATE(81)] = 1536,
  [SMALL_STATE(82)] = 1549,
  [SMALL_STATE(83)] = 1562,
  [SMALL_STATE(84)] = 1575,
  [SMALL_STATE(85)] = 1588,
  [SMALL_STATE(86)] = 1601,
  [SMALL_STATE(87)] = 1614,
  [SMALL_STATE(88)] = 1627,
  [SMALL_STATE(89)] = 1640,
  [SMALL_STATE(90)] = 1644,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expressions, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expressions, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_statements, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statements, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_definition, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_definition, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_definition, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function_definition, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function_definition, 6, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_definition, 6, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_params_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_params_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_params, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_params, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [230] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zoomba(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
